### ISSUE TITLE
Homepage Revisions

### ISSUE THREAD

**Issue by smaraghi** [CSIS-iLab/nuclearnetwork_wp#138]
### Header Transition
- Does not disappear on archive/analysis pages
![image](https://user-images.githubusercontent.com/45780666/133857009-250ead60-e6c3-4563-9547-ccefede80f2f.png)
- There is a point at which it reappears below the border bottom
- Nice to have: smooth transition out

**Comment by urchykli** [comment]
The header for the analysis series archive is in the bug list issue #96 :)
