### ISSUE TITLE
Widget: Newsletters

### ISSUE THREAD

**Issue by urchykli** [CSIS-iLab/nuclearnetwork_wp#42]
Create the newsletter widgets for the footer.

- Create the sidebars in `functions.php`
- Add the `HTML` to the widgets in wp-admin (can look at the [Missile Threat](https://csismtstaging.wpengine.com/wp-admin/) staging site as a guide)
- Add the styles based on each location. You can create a newsletter scss file for the base styling and add the location specific styling to the correct component/layout/page style.
     - Homepage newsletter block `home.scss`
     - Footer `_footer.scss`
     - Program Updates page header `_entry-header.scss`

**Comment by jnschrag** [comment]
Closed by #105
