### ISSUE TITLE
Component: Archive filter

### ISSUE THREAD

**Issue by urchykli** [CSIS-iLab/nuclearnetwork_wp#61]
Build the filters on the archive pages using [FacetWP](https://facetwp.com/documentation/).  You can use [JTI](https://justtransitioninitiative.org/wp-admin/options-general.php?page=facetwp) as an example.

- Analysis has a different filter than the search/tag/general archives. 
- Make sure to include the correct behavior on mobile.
- The authors filter is based on an ACF on the posts

**Comment by jnschrag** [comment]
Closed by #94
