### ISSUE TITLE
Page: About

### ISSUE THREAD

**Issue by urchykli** [CSIS-iLab/nuclearnetwork_wp#66]
Layout the about page

- [ ] Content
- [x] Contact box
- [x] Team members block
- [x] Opportunities block
- [x] Dev team
- [x] About CSIS

**Comment by jnschrag** [comment]
@HP4k1h5 The team members & opportunities block have been created & styled already, but they need to be added to the post on the [dev site](https://csisngnndev.wpengine.com/about/). If you have questions about the blocks, ask @christina-designs who built them out.
