### ISSUE TITLE
Component: Collapsable Date Sidebar

### ISSUE THREAD

**Issue by urchykli** [CSIS-iLab/nuclearnetwork_wp#98]
Create the NPN archive [sidebar](https://www.figma.com/file/cAg0A1ww0s2KbJdIbUvl2j/PONI-Redesign-Handoff?node-id=193%3A199415).

Look [here](https://wordpress.stackexchange.com/questions/344862/how-can-i-group-posts-by-months-and-years) for an example of how to do this.

**Comment by jnschrag** [comment]
Closed by #117
